# Generated by Django 4.2.7 on 2023-11-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
