# Generated by Django 4.2.7 on 2023-11-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0003_alter_competitor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
