# Generated by Django 4.2.7 on 2023-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0005_alter_competitor_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
