# Generated by Django 4.2.7 on 2023-11-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0006_competitor_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='active',
        ),
        migrations.AddField(
            model_name='competitor',
            name='status',
            field=models.CharField(choices=[('ACT', 'ACTIVE'), ('NOM', 'NOMINATED'), ('KIC', 'KICKED')], default='ACT', max_length=3),
        ),
    ]
