# Generated by Django 4.2.7 on 2023-12-13 10:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0007_remove_competitor_active_competitor_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='competitor',
            managers=[
                ('nominated', django.db.models.manager.Manager()),
            ],
        ),
    ]
