# Generated by Django 4.2.7 on 2023-12-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0008_alter_competitor_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='competitor',
            managers=[
            ],
        ),
    ]
