# Generated by Django 4.2.7 on 2023-11-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=250)),
                ('subject', models.CharField(max_length=80)),
                ('avatar', models.ImageField(blank=True, upload_to='teachers/')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
